* DONE Multiple levels
Add a hole that will drop players to a lower level (new world map
query), as well as an item to take them up a level (a rope or portal
or something).
* TODO Visible on-ground items
Probably a new endpoint call to query + display all grabbable items on
the ground.

Note <2019-09-22 Sun> - This seems like a bad idea - it will mean that
the game world would be quite cluttered - a much better feature would
be just auto-loot items and let players horde any number of them, then
make an out of game web UI or something for facilitating trading
(perhaps change item to a uuid code, then uuid code can redeem
item/transfer it).
* DONE Clean up the UI
Particularly for mobile, need a button to flip between move/m/s/a
* TODO Add music / sounds when events occur
Self explanatory
* TODO Need to fix bug with saving data to edn file (it did not persist for some reason)
Probably a better option would just be to add a sqlite layer for
persisting the game, that way writes (such as a single bad one) can't
end up botching the entire game state.
* TODO When mob dies, despawn it next refresh
* TODO Ensure that we stop showing mob on map when they aren't in our zone
Note <2019-09-22 Sun> - I think this one is done?
* TODO Add an optim for gear
We can track last gear changed on server (store the step).  For a
given unit we've drawn, if gear hasn't changed since that step, don't
bother repainting the gear on client.
