# -*- mode: restclient -*-

:url = http://localhost:3000
:username = dad
:step = 1

:headers = <<
content-type: application/json
#

# Check the world state (will block until the step is reached by server)
GET :url/world.json?username=:username&step=:step
#

# Login
POST :url/login.json
:headers
{
  "name": ":username"
}
#

# Do an action (move - others include attack or change stance etc.)
POST :url/input.json
:headers
{
  "action": "move",
  "dir": "E",
  "name": ":username"
}
#

# Pull gear
GET :url/gear.json?username=:username
:headers
#

# Do an action (move - others include attack or change stance etc.)
POST :url/input.json
:headers
{
  "action": "change_gear",
  "head": "2",
  "chest": "3",
  "feet": "4",
  "name": ":username"
}
#
